model_name: loca_few_shot
data_path: /home/nikola/master-thesis/data/fsc147/
model_path: /home/
backbone: resnet50
swav_backbone: false
reduction: 8
image_size: 512
num_enc_layers: 3
num_ope_iterative_steps: 3
emb_dim: 256
num_heads: 8
kernel_dim: 3
num_objects: 3
epochs: 200
resume_training: false
lr: 0.0001
backbone_lr: 0
lr_drop: 200
weight_decay: 0.0001
batch_size: 4
dropout: 0.1
num_workers: 8
max_grad_norm: 0.1
aux_weight: 0.3
tiling_p: 0.5
zero_shot: false
pre_norm: false
